### PR TITLE
Use oconfigure and make

### PR DESCRIPTION
**Pull request by mario-campos**
Meson is nice, but it is an additional dependency to download/install for every platform. I was never happy about this, but it seemed like an acceptable sacrafice rather than support autotools. However, Meson also seemed overkill for my needs, which are to check for the existence of libbsd, etc.

oconfigure is simple and portable...simpler than Meson and autobuild. No extra dependencies.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Depending on what precisely is unpalatable about Meson as an additional dependency, you might be interested in https://sr.ht/~lattis/muon/

It's still an additional dependency compared to systems which are assumed to have Make, but on the other hand, it's a fairly tiny compiled C binary and doesn't pull in a whole python interpreter.

oconfigure does require pulling in some 7k lines worth of vendored code, which is a kind of disadvantage of its own, and interestingly doesn't seem to pick up libbsd automatically anyway

**Comment by mario-campos** [comment]
Ooh, very nice! Thanks!

>oconfigure does require pulling in some 7k lines worth of vendored code, which is a kind of disadvantage of its own, and interestingly doesn't seem to pick up libbsd automatically anyway

Yeah, I'm not crazy about the fact that it doesn't just auto-magically pick up libbsd either.

**Comment by eli-schwartz** [comment]
No problem. Speaking with my Meson dev hat on, we totally understand why people might not be completely happy with Meson's somewhat hefty Python dependency. We have a FAQ entry for it: https://mesonbuild.com/FAQ.html#but-i-really-want-a-version-of-meson-that-doesnt-use-python

(I have contributed patches and advice to the muon developer. The other currently active reimplementation, meson++, was started by another Meson dev. It will be interesting to see where the future leads.)

**Comment by mario-campos** [comment]
@eli-schwartz, thanks for those links and the interest/care. You've convinced me :)

**Comment by eli-schwartz** [comment]
Great, happy to help. :)

Fun fact: two days ago, Muon started publishing statically built x86_64 binaries which weigh in at 4.5mb, which frames the "how big is this dependency" question quite nicely. (Yes, that includes `muon samu` as a builtin copy of samurai for executing `build.ninja`, so you don't need an external ninja either.)

Quite nice when you consider python is around 50mb plus 3.5mb for Meson itself, and cmake is a 61mb download without even the excuse of needing an interpreter dependency.

**Pull request closed without merging**
